# Generated by Django 2.1.3 on 2018-11-19 00:12

from django.db import migrations, models
import news.timestamp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.CharField(default='', max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('date_time', news.timestamp.UnixTimestampField(null=True)),
            ],
        ),
    ]
