# Generated by Django 2.1.7 on 2019-02-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190222_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='category_type',
        ),
    ]
